### ISSUE TITLE
Hidden dependencies betwen tests - `Router.test.ts` makes `_ConstantProduct.test.ts` if run before

### ISSUE THREAD

**Issue by cameel** [sushiswap/trident#303]
### Summary
There seems to be an implicit dependency between test suites because whether they fail or not depends on their order. In particular `_ConstantProduct.test.ts` fails if you run `Router.test.ts` before it.

This is especially problematic because to work around #283 I need to exclude some tests. Hardhat does not seem to have a command-line option for that so I'm doing it like this:
```bash
tests_to_run=$(find test/ -name "*.test.ts" ! -path "test/Migration.test.ts")
npx hardhat test $tests_to_run
```
This unfortunately may produce a different order than the one Hardhat uses.

#### `_ConstantProduct.test.ts` and `Router.test.ts`
This fails:
```bash
npx hardhat test test/Router.test.ts test/constant-product/_ConstantProduct.test.ts
```
```
  Constant Product Pool Old
    1) "before all" hook in "Constant Product Pool Old"


  9 passing (6s)
  1 failing

  1) Constant Product Pool Old
       "before all" hook in "Constant Product Pool Old":

      AssertionError: expected '0x4B8297ba8ab03Ad9Dc81d09edD9EAB58e7d1100a' to equal '0xAD806Ef1a19DB65F12C08E0f6101Eb4cD5004CCd'
      + expected - actual

      -0x4B8297ba8ab03Ad9Dc81d09edD9EAB58e7d1100a
      +0xAD806Ef1a19DB65F12C08E0f6101Eb4cD5004CCd

      at initialize (test/harness/ConstantProduct.ts:99:25)
      at async Context.<anonymous> (test/constant-product/_ConstantProduct.test.ts:8:5)
```
Reversing the order fixes the problem:
```bash
npx hardhat test test/constant-product/_ConstantProduct.test.ts test/Router.test.ts
```
```
  Constant Product Pool Old
    #swap
      ✓ Should do 24 types of swaps (3300ms)
    #mint
      ✓ Balanced liquidity to a balanced pool (109ms)
      ✓ Add liquidity in 16 different ways before swap fees (1938ms)
      ✓ Add liquidity in 16 different ways after swap fees (1973ms)
    #burn
      ✓ Remove liquidity in 12 different ways (2649ms)

...

  14 passing (18s)
```

#### Sorted paths
If you sort the paths to work around it, it still fails, the errors are just different. The test suite seems to be very brittle with regard to test ordering.
```bash
tests_to_run=$(find test/ -name "*.test.ts" ! -path "test/Migration.test.ts" | LC_ALL=C sort)
npx hardhat test $tests_to_run
```
```
  113 passing (3m)
  3 pending
  2 failing

  1) Constant Product Pool Old
       #mint
         Add liquidity in 16 different ways before swap fees:

      AssertionError: Expected "49000000000000000000" to be equal 0
      + expected - actual

       {
      -  "_hex": "0x00"
      +  "_hex": "0x02a802f8630a240000"
         "_isBigNumber": true
       }

      at assertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:58:54)
      at tryAssertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:65:20)
      at /tmp/ext-test-Trident-fjO08G/ext/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:77:13
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:536:9)
      at processTimers (node:internal/timers:510:7)
      at async addLiquidity (test/harness/ConstantProduct.ts:149:3)
      at async addLiquidityInMultipleWays (test/constant-product/_ConstantProduct.test.ts:73:7)

  2) Constant Product Pool Old
       #mint
         Add liquidity in 16 different ways after swap fees:

      AssertionError: Expected "35000000000000000000" to be equal 0
      + expected - actual

       {
      -  "_hex": "0x00"
      +  "_hex": "0x01e5b8fa8fe2ac0000"
         "_isBigNumber": true
       }

      at assertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:58:54)
      at tryAssertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:65:20)
      at /tmp/ext-test-Trident-fjO08G/ext/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:77:13
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:536:9)
      at processTimers (node:internal/timers:510:7)
      at async addLiquidity (test/harness/ConstantProduct.ts:149:3)
      at async addLiquidityInMultipleWays (test/constant-product/_ConstantProduct.test.ts:73:7)
```

**Comment by matthewlilley** [comment]
@cameel Yeah, I've had to hack my way around this for the time being. I'll refactor these old file asap.

**Comment by cameel** [comment]
Thanks!

Any chance you could take a look at #283 as well?
